### ISSUE TITLE
hi, 如果强行结束掉 shadowsocks， localhost的 port不会被立即释放。

### ISSUE THREAD

**Issue by sniperpr** [zhao-gang/shadowsocks-tiny#3]
hi, 如果强行结束掉 shadowsocks， localhost的 port不会被立即释放。

**Comment by clarkwang** [comment]
+1. Please fix this problem.

**Comment by zhao-gang** [comment]
Better late than never :) 

Fixed in 02777ad6f5be04fc0ec5f1bb4a3120e82a85d72a
